Somativa/Models/VendaItem.cs
using System.ComponentModel;

namespace Somativa.Models
{
    public class VendaItem
    {
        public Guid VendaItemId { get; set; }
        [DisplayName("Nota Fiscal")]
        public Guid VendaId { get; set; }
        public Venda? Venda { get; set; }
        [DisplayName("Produto")]
        public Guid ProdutoId { get; set; }
        public Produto? Produto { get; set; }
        public int Quantidade { get; set; }
        public decimal Unitario { get; set; }
    }
}

Somativa/Controllers/VendaItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Somativa.Data;
using Somativa.Models;

namespace Somativa.Controllers
{
	[Authorize(Roles = "Admin,Operador")]
	public class VendaItemsController : Controller
    {
        private readonly SprintContext _context;

        public VendaItemsController(SprintContext context)
        {
            _context = context;
        }

        // GET: VendaItems
        public async Task<IActionResult> Index(Guid Id)
        {
            var sprintContext = _context.VendaItens.Include(v => v.Produto).Include(v => v.Venda);
            ViewData["VendaId"] =  Id ;
            return View(await sprintContext.Where(i => i.VendaId==Id).ToListAsync());
        }

        // GET: VendaItems/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null || _context.VendaItens == null)
            {
                return NotFound();
            }

            var vendaItem = await _context.VendaItens
                .Include(v => v.Produto)
                .Include(v => v.Venda)
                .FirstOrDefaultAsync(m => m.VendaItemId == id);
            if (vendaItem == null)
            {
                return NotFound();
            }

            return View(vendaItem);
        }

        // GET: VendaItems/Create
        public IActionResult Create(Guid Id)
        {
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome");
            
            //ViewData["VendaId"] = new SelectList(_context.Vendas, "VendaId", "Nome");
            ViewData["VendaId"] = Id;          
            return View();
        }

        // POST: VendaItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("VendaItemId,VendaId,ProdutoId,Quantidade,Unitario")] VendaItem vendaItem)
        {
            if (ModelState.IsValid)
            {
                vendaItem.VendaItemId = Guid.NewGuid();
                _context.Add(vendaItem);
                await _context.SaveChangesAsync();

                Produto p = _context.Produtos.Where(p => p.ProdutoId == vendaItem.ProdutoId).FirstOrDefault();
                p.Estoque -= vendaItem.Quantidade;
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index), new {Id = vendaItem.VendaId});
            }
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Produto", vendaItem.ProdutoId);
            ViewData["VendaId"] = new SelectList(_context.Vendas, "VendaId", "Nota", vendaItem.VendaId);
                      

            return View(vendaItem);
        }

        // GET: VendaItems/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null || _context.VendaItens == null)
            {
                return NotFound();
            }

            var vendaItem = await _context.VendaItens.FindAsync(id);
            if (vendaItem == null)
            {
                return NotFound();
            }
            //ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Produto");
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Nome");
            ViewData["VendaId"] = new SelectList(_context.Vendas, "VendaId", "Nota", vendaItem.VendaId);
            return View(vendaItem);
        }

        // POST: VendaItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("VendaItemId,VendaId,ProdutoId,Quantidade,Unitario")] VendaItem vendaItem)
        {
            if (id != vendaItem.VendaItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vendaItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VendaItemExists(vendaItem.VendaItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProdutoId"] = new SelectList(_context.Produtos, "ProdutoId", "Produto", vendaItem.ProdutoId);
            ViewData["VendaId"] = new SelectList(_context.Vendas, "VendaId", "Nota", vendaItem.VendaId);
            return View(vendaItem);
        }

        // GET: VendaItems/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null || _context.VendaItens == null)
            {
                return NotFound();
            }

            var vendaItem = await _context.VendaItens
                .Include(v => v.Produto)
                .Include(v => v.Venda)
                .FirstOrDefaultAsync(m => m.VendaItemId == id);
            if (vendaItem == null)
            {
                return NotFound();
            }

            return View(vendaItem);
        }

        // POST: VendaItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            if (_context.VendaItens == null)
            {
                return Problem("Entity set 'SprintContext.VendaItens'  is null.");
            }
            var vendaItem = await _context.VendaItens.FindAsync(id);
            if (vendaItem != null)
            {
                _context.VendaItens.Remove(vendaItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VendaItemExists(Guid id)
        {
          return (_context.VendaItens?.Any(e => e.VendaItemId == id)).GetValueOrDefault();
        }
    }
}

Somativa/Views/VendaItems/Create.cshtml
@model Somativa.Models.VendaItem

@{
    ViewData["Title"] = "Create";
    var VendaIdAux = ViewData["VendaId"];
}


<h4 class="text-center">Adicionar Item a Venda</h4>
<hr />
<div class="row justify-content-center align-content-center text-center">
    <div class="col-md-4 text-center">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="VendaId" />
            <div class="form-floating mb-3">
                <select asp-for="VendaId" class="form-control" asp-items="ViewBag.ClienteId"></select>
                <label asp-for="VendaId" class="control-label"></label>
                <span asp-validation-for="VendaId" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <select asp-for="ProdutoId" class="form-control" asp-items="ViewBag.ClienteId"></select>
                <label asp-for="ProdutoId" class="control-label"></label>
                <span asp-validation-for="ProdutoId" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Quantidade" class="form-control" id="inData" placeholder="name" />
                <label asp-for="Quantidade" for="inData">Data e Hora</label>
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Unitario" class="form-control" id="inData" placeholder="name" />
                <label asp-for="Unitario" for="inData">Data e Hora</label>
                <span asp-validation-for="Unitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
                <a asp-controller="VendaItems" asp-action="Index"><svg bootstrap-icon="ArrowLeft" width="24" height="24" aria-label="Alarms"></svg></a>
            </div>
        </form>
    </div>
</div>
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Somativa/Views/VendaItems/Delete.cshtml
@model Somativa.Models.VendaItem

@{
    ViewData["Title"] = "Delete";
}

<div class="container text-center">
    <h3 class="alert-danger p-2">Certeza que quer apagar?</h3>
    <div>
        <hr />
        <h4>Vendas Itens</h4>
        <div>
            <dl class="row">
                <p class="col-sm-12">@Html.DisplayNameFor(model => model.Venda):  @Html.DisplayFor(model => model.Venda.Nota)</p>
                <p class="col-sm-12">@Html.DisplayNameFor(model => model.Produto): @Html.DisplayNameFor(model => model.Produto.Nome)</p>
                <p class="col-sm-12">@Html.DisplayNameFor(model => model.Quantidade): @Html.DisplayFor(model => model.Quantidade)</p>
                <p class="col-sm-12">@Html.DisplayNameFor(model => model.Unitario) R$: @Html.DisplayFor(model => model.Unitario)</p>
            </dl>
            <form asp-action="Delete">
                <input type="hidden" asp-for="VendaId" />
                <input type="submit" value="Apagar" class="btn btn-danger" /> |
                <a asp-controller="VendaItems" asp-action="Index" asp-route-id=@Model.VendaId><svg bootstrap-icon="ArrowLeft" width="24" height="24" aria-label="Alarms"></svg></a>
            </form>
        </div>
    </div>
</div>

Somativa/Views/VendaItems/Details.cshtml
@model Somativa.Models.VendaItem

@{
    ViewData["Title"] = "Details";
}

<div class="container justify-content-center align-content-center text-center">
    <h1>Detalhes</h1>
    <div>
        <h4>Venda</h4>
        <hr />
        <dl class="row">
            <p class="col-sm-12">@Html.DisplayNameFor(model => model.Venda):  @Html.DisplayFor(model => model.Venda.Nota)</p>
            <p class="col-sm-12">@Html.DisplayNameFor(model => model.Produto): @Html.DisplayNameFor(model => model.Produto.Nome)</p>
            <p class="col-sm-12">@Html.DisplayNameFor(model => model.Quantidade): @Html.DisplayFor(model => model.Quantidade)</p>
            <p class="col-sm-12">@Html.DisplayNameFor(model => model.Unitario) R$: @Html.DisplayFor(model => model.Unitario)</p>
        </dl>
        <div>
            <a asp-action="Edit" asp-route-id="@Model?.VendaItemId"><svg bootstrap-icon="Pen" width="24" height="24" aria-label="Alarms"></svg></a> |
            <a asp-controller="VendaItems" asp-action="Index" asp-route-id=@Model.VendaId><svg bootstrap-icon="ArrowLeft" width="24" height="24" aria-label="Alarms"></svg></a>
        </div>
    </div>
</div>

Somativa/Views/VendaItems/Edit.cshtml
@model Somativa.Models.VendaItem

@{
    ViewData["Title"] = "Edit";
}

<h4 class="text-center">Editar </h4>
<hr />
<div class="row justify-content-center align-content-center text-center">
    <div class="col-md-4 text-center">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="VendaItemId" />      
            <div class="form-floating mb-3">
                <select asp-for="VendaId" id="inNota" class="form-control" asp-items="ViewBag.VendaId"></select>
                <label asp-for="VendaId" class="control-label" for="inNota"></label>
                <span asp-validation-for="VendaId" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <select asp-for="ProdutoId" id="inNota" class="form-control" asp-items="ViewBag.ProdutoId"></select>
                <label asp-for="ProdutoId" class="control-label" for="inNota"></label>
                <span asp-validation-for="ProdutoId" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Quantidade" class="form-control" id="inNota" placeholder="name" />
                <label asp-for="Quantidade" class="control-label" for="inNota"></label>
                <span asp-validation-for="Quantidade" class="text-danger"></span>
            </div>
            <div class="form-floating mb-3">
                <input asp-for="Unitario" class="form-control" id="inNota" placeholder="name" />
                <label asp-for="Unitario" class="control-label" for="inNota"></label>
                <span asp-validation-for="Unitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Aplicar Alterações" class="btn btn-primary" />
                <a asp-controller="VendaItems" asp-action="Index" asp-route-id=@Model.VendaId><svg bootstrap-icon="ArrowLeft" width="24" height="24" aria-label="Alarms"></svg></a>
            </div>
        </form>

    </div>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Somativa/Views/VendaItems/Index.cshtml
@model IEnumerable<Somativa.Models.VendaItem>

@{
    ViewData["Title"] = "Index";
    var VendaIdAux = ViewData["VendaId"];
}

<h1 class="text-center">Itens</h1>
<div class="table-responsive">

<table class="table table-responsive table-striped table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Venda)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Produto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantidade)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Unitario)
            </th>
            <th class="text-end"><a asp-action="Create" asp-route-id="@ViewData["VendaId"]" class="text-decoration-none text-black">Adicionar<span class="badge"><svg bootstrap-icon="PlusCircle" width="18" height="18" aria-label="Alarms" class="bg-white text-black"></svg></span></a></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Venda.Nota)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Produto.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantidade)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Unitario)
                </td>
                <td class="text-end">
                    <a asp-action="Edit" asp-route-id="@item.VendaItemId" class="btn btn-primary"><svg bootstrap-icon="PencilFill" width="12" height="12" aria-label="Alarms"></svg></a>
                    <a asp-action="Details" asp-route-id="@item.VendaItemId" class="btn btn-info"><svg bootstrap-icon="Search" width="12" height="12 aria-label="Alarms"></svg></a>
                    <a asp-action="Delete" asp-route-id="@item.VendaItemId" class="btn btn-danger"><svg bootstrap-icon="Trash2Fill" width="12" height="12" aria-label="Alarms"></svg></a>               
                </td>
            </tr>
        }
    </tbody>
</table>
</div>